# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [1]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

def BMI_calc(height, weight):
    height = np.array(height)
    weight = np.array(weight)
    bmi = weight / (height**2) * 730
    return bmi

BMI_calc(height, weight)

array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [39]:
import numpy as np

def random_matrix(x, y):
    M = np.random.randint(x, y, ((int(input("How many rows? "))), (int(input("How many columns?" )))))
    data_type = input("What data type for this matrix? \nfloat, int, or str:\n ")
    final_M = M.astype(data_type)
    return final_M
    
print(random_matrix(5, 200))
    
    


How many rows? 3
How many columns?3
What data type for this matrix? 
float, int, or str:
 int
[[103  32 110]
 [ 44  46 188]
 [196  70 102]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [1]:
import csv
import numpy as np

In [2]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray
def load_data(filename, d = ','):
    data = np.genfromtxt(filename,delimiter = d, skip_header = 1,
                        usecols = np.arange(0,28),invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('../Data_Python_Files/redsox_2017_hitting.txt')
bs2018 = load_data('../Data_Python_Files/redsox_2018_hitting.txt')

SLG_avg_17 = sum(bs2017['SLG']) / len(bs2017['SLG'])
SLG_avg_18 = sum(bs2018['SLG']) / len(bs2018['SLG'])

print(f"\nAvg SLG for 2017: {SLG_avg_17}")
print(f"\nAvg SLG for 2018: {SLG_avg_18}")

if SLG_avg_17 > SLG_avg_18:
    print("\n2017 was a better year based on SLG")
else:
    print("\n2018 was a better year based on SLG")


Avg SLG for 2017: 0.39334782374941785

Avg SLG for 2018: 0.38750000335276125

2017 was a better year based on SLG
